# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

equalpairs <- function(u, v, ou, ov, max_number_of_pairs) {
    .Call(`_testxyz1_equalpairs`, u, v, ou, ov, max_number_of_pairs)
}

FibCpp0 <- function(n) {
    .Call(`_testxyz1_FibCpp0`, n)
}

findIndex <- function(array, value) {
    .Call(`_testxyz1_findIndex`, array, value)
}

generate_uniform_values <- function(n, a = 0.0, b = 1.0) {
    .Call(`_testxyz1_generate_uniform_values`, n, a, b)
}

generate_random_projection <- function(n, M, with_replacement) {
    .Call(`_testxyz1_generate_random_projection`, n, M, with_replacement)
}

equal_pairs <- function(u, v, max_number_of_pairs) {
    .Call(`_testxyz1_equal_pairs`, u, v, max_number_of_pairs)
}

interaction_strength <- function(X, Y, j, k) {
    .Call(`_testxyz1_interaction_strength`, X, Y, j, k)
}

push <- function(M, new_vector) {
    .Call(`_testxyz1_push`, M, new_vector)
}

strongest_pairs <- function(X, Y, M, L, gamma) {
    .Call(`_testxyz1_strongest_pairs`, X, Y, M, L, gamma)
}

generateMatrix <- function(n, p) {
    .Call(`_testxyz1_generateMatrix`, n, p)
}

go <- function(n) {
    .Call(`_testxyz1_go`, n)
}

