# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FibCpp0 <- function(n) {
    .Call(`_testxyz1_FibCpp0`, n)
}

findIndex <- function(array, value) {
    .Call(`_testxyz1_findIndex`, array, value)
}

binaryToInt <- function(matrix) {
    .Call(`_testxyz1_binaryToInt`, matrix)
}

sorted_index_vector <- function(v) {
    .Call(`_testxyz1_sorted_index_vector`, v)
}

apply_permutation <- function(vec, p) {
    .Call(`_testxyz1_apply_permutation`, vec, p)
}

combine <- function(x, y) {
    .Call(`_testxyz1_combine`, x, y)
}

push <- function(M, new_vector) {
    invisible(.Call(`_testxyz1_push`, M, new_vector))
}

find <- function(v, k) {
    .Call(`_testxyz1_find`, v, k)
}

pair_search3 <- function(x, y) {
    .Call(`_testxyz1_pair_search3`, x, y)
}

findindexit <- function(vec, n) {
    .Call(`_testxyz1_findindexit`, vec, n)
}

binarySearchIndex <- function(v, n) {
    .Call(`_testxyz1_binarySearchIndex`, v, n)
}

pair_search6 <- function(x, sorted_indexes) {
    .Call(`_testxyz1_pair_search6`, x, sorted_indexes)
}

pair_search7 <- function(x, sorted_indexes) {
    .Call(`_testxyz1_pair_search7`, x, sorted_indexes)
}

groupt <- function(list, sorted, n1) {
    .Call(`_testxyz1_groupt`, list, sorted, n1)
}

splitVectors <- function(inputList, n) {
    .Call(`_testxyz1_splitVectors`, inputList, n)
}

group2 <- function(list, sorted, n1) {
    .Call(`_testxyz1_group2`, list, sorted, n1)
}

pair_search4 <- function(x, y) {
    .Call(`_testxyz1_pair_search4`, x, y)
}

test4 <- function(x, sorted_indexes) {
    .Call(`_testxyz1_test4`, x, sorted_indexes)
}

expandGrid <- function(vec1, vec2) {
    .Call(`_testxyz1_expandGrid`, vec1, vec2)
}

pair_search8 <- function(x, y) {
    .Call(`_testxyz1_pair_search8`, x, y)
}

test3 <- function(x, sorted_indexes) {
    .Call(`_testxyz1_test3`, x, sorted_indexes)
}

cantor_map <- function(pairs) {
    .Call(`_testxyz1_cantor_map`, pairs)
}

inverse_cantor_map <- function(values) {
    .Call(`_testxyz1_inverse_cantor_map`, values)
}

normalizeL1 <- function(vec) {
    .Call(`_testxyz1_normalizeL1`, vec)
}

transformY <- function(vec) {
    .Call(`_testxyz1_transformY`, vec)
}

uniformSampling <- function(X, Y, p, k) {
    .Call(`_testxyz1_uniformSampling`, X, Y, p, k)
}

weightedSampling <- function(X, Y, p, k) {
    .Call(`_testxyz1_weightedSampling`, X, Y, p, k)
}

getunique <- function(combined) {
    .Call(`_testxyz1_getunique`, combined)
}

hadamard <- function(x, y) {
    .Call(`_testxyz1_hadamard`, x, y)
}

inner_product <- function(x, y) {
    .Call(`_testxyz1_inner_product`, x, y)
}

filter <- function(pairs, X, Y, threshold) {
    .Call(`_testxyz1_filter`, pairs, X, Y, threshold)
}

generate_uniform_values <- function(n, a = 0.0, b = 1.0) {
    .Call(`_testxyz1_generate_uniform_values`, n, a, b)
}

generate_random_projection <- function(n, M, with_replacement) {
    .Call(`_testxyz1_generate_random_projection`, n, M, with_replacement)
}

binary_search_cpp <- function(arr, target) {
    .Call(`_testxyz1_binary_search_cpp`, arr, target)
}

interaction_strength <- function(X, Y, j, k) {
    .Call(`_testxyz1_interaction_strength`, X, Y, j, k)
}

find_pair_matches <- function(x0, z0) {
    .Call(`_testxyz1_find_pair_matches`, x0, z0)
}

find_pair_matches2 <- function(x0, z0) {
    .Call(`_testxyz1_find_pair_matches2`, x0, z0)
}

strongest_pairs <- function(X, Y, M, L, gamma) {
    .Call(`_testxyz1_strongest_pairs`, X, Y, M, L, gamma)
}

strongest_pairs_binary <- function(X, Y) {
    .Call(`_testxyz1_strongest_pairs_binary`, X, Y)
}

cut <- function(input_vec) {
    .Call(`_testxyz1_cut`, input_vec)
}

generateMatrix <- function(n, p) {
    .Call(`_testxyz1_generateMatrix`, n, p)
}

random_binary_matrix <- function(n, p) {
    .Call(`_testxyz1_random_binary_matrix`, n, p)
}

random_binary_vector <- function(n) {
    .Call(`_testxyz1_random_binary_vector`, n)
}

go <- function(n, p) {
    .Call(`_testxyz1_go`, n, p)
}

r <- function(n, minValue = 0L, maxValue = 10L) {
    .Call(`_testxyz1_r`, n, minValue, maxValue)
}

rs <- function(n, minValue = 0L, maxValue = 100L) {
    .Call(`_testxyz1_rs`, n, minValue, maxValue)
}

makeZ <- function(X, Y) {
    .Call(`_testxyz1_makeZ`, X, Y)
}

equalpairs <- function(u, v, ou, ov, max_number_of_pairs) {
    .Call(`_testxyz1_equalpairs`, u, v, ou, ov, max_number_of_pairs)
}

equalpairs2 <- function(u, v, ou, ov, max_number_of_pairs) {
    .Call(`_testxyz1_equalpairs2`, u, v, ou, ov, max_number_of_pairs)
}

expandGrido <- function(vec1, vec2) {
    .Call(`_testxyz1_expandGrido`, vec1, vec2)
}

pairsearch9 <- function(a_positions, b_positions, a_sorted_values, b_sorted_values) {
    .Call(`_testxyz1_pairsearch9`, a_positions, b_positions, a_sorted_values, b_sorted_values)
}

pairsearch10 <- function(a_positions, b_positions, a_sorted_values, b_sorted_values) {
    .Call(`_testxyz1_pairsearch10`, a_positions, b_positions, a_sorted_values, b_sorted_values)
}

