# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

equalpairs <- function(u, v, ou, ov, max_number_of_pairs) {
    .Call(`_testxyz1_equalpairs`, u, v, ou, ov, max_number_of_pairs)
}

FibCpp0 <- function(n) {
    .Call(`_testxyz1_FibCpp0`, n)
}

findIndex <- function(array, value) {
    .Call(`_testxyz1_findIndex`, array, value)
}

sorted_index_vector <- function(v) {
    .Call(`_testxyz1_sorted_index_vector`, v)
}

apply_permutation <- function(vec, p) {
    .Call(`_testxyz1_apply_permutation`, vec, p)
}

combine <- function(x, y) {
    .Call(`_testxyz1_combine`, x, y)
}

push <- function(M, new_vector) {
    invisible(.Call(`_testxyz1_push`, M, new_vector))
}

find <- function(v, k) {
    .Call(`_testxyz1_find`, v, k)
}

pair_search3 <- function(x, y) {
    .Call(`_testxyz1_pair_search3`, x, y)
}

generate_uniform_values <- function(n, a = 0.0, b = 1.0) {
    .Call(`_testxyz1_generate_uniform_values`, n, a, b)
}

generate_random_projection <- function(n, M, with_replacement) {
    .Call(`_testxyz1_generate_random_projection`, n, M, with_replacement)
}

binary_search_cpp <- function(arr, target) {
    .Call(`_testxyz1_binary_search_cpp`, arr, target)
}

interaction_strength <- function(X, Y, j, k) {
    .Call(`_testxyz1_interaction_strength`, X, Y, j, k)
}

binaryToInt <- function(matrix) {
    .Call(`_testxyz1_binaryToInt`, matrix)
}

find_pair_matches <- function(x0, z0) {
    .Call(`_testxyz1_find_pair_matches`, x0, z0)
}

find_pair_matches2 <- function(x0, z0) {
    .Call(`_testxyz1_find_pair_matches2`, x0, z0)
}

strongest_pairs <- function(X, Y, M, L, gamma) {
    .Call(`_testxyz1_strongest_pairs`, X, Y, M, L, gamma)
}

strongest_pairs_binary <- function(X, Y) {
    .Call(`_testxyz1_strongest_pairs_binary`, X, Y)
}

cut <- function(input_vec) {
    .Call(`_testxyz1_cut`, input_vec)
}

generateMatrix <- function(n, p) {
    .Call(`_testxyz1_generateMatrix`, n, p)
}

random_binary_matrix <- function(n, p) {
    .Call(`_testxyz1_random_binary_matrix`, n, p)
}

random_binary_vector <- function(n) {
    .Call(`_testxyz1_random_binary_vector`, n)
}

go <- function(n, p) {
    .Call(`_testxyz1_go`, n, p)
}

vec1 <- function(n = 0L) {
    .Call(`_testxyz1_vec1`, n)
}

vec2 <- function(n = 0L) {
    .Call(`_testxyz1_vec2`, n)
}

r <- function(n, minValue = 0L, maxValue = 10L) {
    .Call(`_testxyz1_r`, n, minValue, maxValue)
}

